export const PERFIS = ["ADMIN", "GESTOR", "ATENDENTE", "TECNICO", "CLIENTE"];

export const ESTADOS_CONSERVACAO = [
  "NOVO",
  "SEMINOVO",
  "USADO_BOM",
  "USADO_REGULAR",
  "RECONDICIONADO",
];

export const FORMAS_PAGAMENTO = [
  "DINHEIRO",
  "PIX",
  "CARTAO_CREDITO",
  "CARTAO_DEBITO",
  "BOLETO",
  "TRANSFERENCIA",
  "OUTRA",
];

export const TIPOS_RECEITA = ["VENDA", "SERVICO", "PECA", "OUTRA"];

export const TIPOS_DESPESA = [
  "COMPRA_PECA",
  "ALUGUEL",
  "SALARIO",
  "MANUTENCAO",
  "CONTA_LUZ",
  "INTERNET",
  "TRANSPORTE",
  "FERRAMENTA",
  "IMPOSTO",
  "OUTRA",
];

export const STATUS_ORDEM_SERVICO = [
  "ABERTA",
  "EM_ANALISE",
  "AGUARDANDO_ORCAMENTO",
  "AGUARDANDO_APROVACAO",
  "EM_EXECUCAO",
  "FINALIZADA",
  "CANCELADA",
];

export const TIPOS_HISTORICO_OS = [
  "ABERTURA",
  "ATRIBUICAO_TECNICO",
  "ALTERACAO_STATUS",
  "DIAGNOSTICO",
  "SOLUCAO",
  "FINALIZACAO",
  "CANCELAMENTO",
  "OBSERVACAO",
];

export const TIPOS_MOVIMENTACAO = ["ENTRADA", "SAIDA", "AJUSTE"];
